name: Auto Update README

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 6 hours (change this if needed)
  workflow_dispatch:        # Optional: allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run the update_readme.py script
        run: python update_readme.py

      - name: Commit and push if README.md changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Auto-update README"
          git push
