name: Auto Update README

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (for testing)
  workflow_dispatch:        # Manual trigger support

permissions:
  contents: write  # 👈 Required for push access

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 👈 Makes push authorized

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run the update_readme.py script
        run: python update_readme.py

      - name: Commit and push if README.md changed
        run: |
          git config --global user.name "codewithajoydas"
          git config --global user.email "codewithajoydas@gmail.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update README"
            git push
          
